services:
  app:
    networks:
      - hawk_keycloak_net
      - default
    environment:
      # Preconfigured with our local testing environment: https://github.com/HAWK-Digital-Environments/hawk-keycloak-infrastructure
      # Do not worry about the values, they are not sensitive.
      - REDIRECT_URI=http://localhost:8099
      - CLIENT_ID=hawk
      - CLIENT_SECRET=RHQjrfnuMcYDJqepveiGNDH45ZtpFrLv
      - REALM=dev
      - PUBLIC_KEYCLOAK_URL=http://localhost:8088
      - INTERNAL_KEYCLOAK_URL=http://keycloak:8080
networks:
  hawk_keycloak_net:
    external: true
