services:
  app:
    container_name: auth-client-examples-app
    build:
      context: ..
      dockerfile: examples/Dockerfile
    volumes:
      - .:/var/www/html-examples
      - ./app:/var/www/html
      - ../:/var/www/html-composer/auth-client
      - ../frontend/dist:/var/www/html/public/frontend
    environment:
      - REDIRECT_URI=http://localhost:8099
      - CLIENT_ID=YOUR_CLIENT_ID
      - CLIENT_SECRET=YOUR_CLIENT_SECRET
      - REALM=YOUR_REALM
      - PUBLIC_KEYCLOAK_URL=http://localhost:8080
      - INTERNAL_KEYCLOAK_URL=''
    ports:
      - ${DOCKER_PROJECT_IP:-127.0.0.1}:8099:80
    extra_hosts:
      - host.docker.internal:host-gateway
