name: Create new Release (Frontend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'examples/**'
      - '.github/workflows/frontend.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5
        with:
          version-file: './frontend/package.json'
          github-token: ${{ secrets.github_token }}
          output-file: 'false'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Publish to NPM
        working-directory: ./frontend
        run: npm publish --access public
